// Generated by ts-to-zod
import { z } from "zod";

export const friendSchema = z.object({
  id: z.number(),
  username: z.string(),
});

export const userSchema = z.object({
  id: z.number(),
  name: z.string(),
  username: z.string(),
  email: z.string(),
  age: z.number(),
  power: z.string(),
  password: z.string(),
  friends: z.array(friendSchema),
});
